/*
 * Copyright (c) 2026 404Setup. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
 */

/**
 * Re-exports generated protobuf message types (snake_case field names).
 * Generated by `npm run proto` / build.mjs from proto/api/v1/api.proto.
 */
import {renop} from './api.js';

const v1 = renop.api.v1;

export const InstanceStatus = v1.InstanceStatus;
export const UpdateState = v1.UpdateState;
export const StatusSnapshotList = v1.StatusSnapshotList;
export const SessionDetails = v1.SessionDetails;
export const LoginRequest = v1.LoginRequest;
export const SessionDto = v1.SessionDto;
export const SessionList = v1.SessionList;
export const StatusOk = v1.StatusOk;
export const AccessTokenList = v1.AccessTokenList;
export const MavenRepositoriesResponse = v1.MavenRepositoriesResponse;
export const Repository = v1.Repository;
export const FileDetails = v1.FileDetails;
export const RepoDetailsResponse = v1.RepoDetailsResponse;
export const RebuildIndexRequest = v1.RebuildIndexRequest;
export const SettingsDomainsResponse = v1.SettingsDomainsResponse;
export const FrontendConfig = v1.FrontendConfig;
export const ServerConfig = v1.ServerConfig;
export const StorageConfig = v1.StorageConfig;
export const UpdaterConfig = v1.UpdaterConfig;
export const DatabaseConfig = v1.DatabaseConfig;
export const IndexDomainSettings = v1.IndexDomainSettings;
export const GpgConfig = v1.GpgConfig;
export const ProxyConfig = v1.ProxyConfig;
export const ChunkedUploadInitRequest = v1.ChunkedUploadInitRequest;
export const ChunkedUploadInitResponse = v1.ChunkedUploadInitResponse;
export const ChunkedUploadCompleteResponse = v1.ChunkedUploadCompleteResponse;
export const ErrorMessage = v1.ErrorMessage;
export const FidoDeviceDto = v1.FidoDeviceDto;
export const FidoDeviceList = v1.FidoDeviceList;
export const GpgKeyReferenceRequest = v1.GpgKeyReferenceRequest;
export const GpgKeyDto = v1.GpgKeyDto;
export const GpgKeyList = v1.GpgKeyList;
export const GpgSignatureDetails = v1.GpgSignatureDetails;
export const GpgReleaseDto = v1.GpgReleaseDto;
export const GpgReleaseList = v1.GpgReleaseList;
export const UpdatePasswordRequest = v1.UpdatePasswordRequest;
export const GenerateTokenResponse = v1.GenerateTokenResponse;
export const CreateAccessTokenRequest = v1.CreateAccessTokenRequest;
export const CreateAccessTokenResponse = v1.CreateAccessTokenResponse;
export const VersionsResponse = v1.VersionsResponse;
export const LatestVersionResponse = v1.LatestVersionResponse;
export const PomDetails = v1.PomDetails;
export const AuditLogEntryDto = v1.AuditLogEntryDto;
export const AuditLogList = v1.AuditLogList;
export const UserMessageDto = v1.UserMessageDto;
export const UserMessageList = v1.UserMessageList;
export const UnreadCountResponse = v1.UnreadCountResponse;
export const MarkAllReadResponse = v1.MarkAllReadResponse;
export const ClearMessagesResponse = v1.ClearMessagesResponse;
export const SendNotificationRequest = v1.SendNotificationRequest;
export const SendNotificationResponse = v1.SendNotificationResponse;
export const UserSearchResponse = v1.UserSearchResponse;
export const RepositorySearchResult = v1.RepositorySearchResult;
export const RepositorySearchResponse = v1.RepositorySearchResponse;

/** Options so decoded objects keep snake_case and numeric 64-bit fields. */
export const protoObjectOptions = {
    longs: Number,
    enums: String,
    bytes: String,
    defaults: true,
    arrays: true,
    objects: true,
    oneofs: true,
};
