/*
 * Copyright (c) 2026 404Setup. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
 */

package cargo

import (
	"context"
	"path/filepath"
	"strings"

	"github.com/gofiber/fiber/v3"

	"renop/internal/config"
	"renop/internal/core"
	"renop/internal/service/repositorygate"
)

// Handler routes Cargo-specific endpoints. Persistence remains behind Store so
// the protocol implementation does not depend on local-disk or S3 internals.
type Handler struct {
	Store Store
	// UpstreamIndexExists performs an authoritative, non-caching sparse-index
	// name check before a local package is created.
	UpstreamIndexExists func(context.Context, *core.AppState, *config.Repository, string) (bool, error)
}

// Handle intercepts Cargo-only paths. The bool is true when the path belongs
// to Cargo, including errors generated by the endpoint.
func (h Handler) Handle(c fiber.Ctx, state *core.AppState, repo *config.Repository, storagePath, requestPath string) (bool, error) {
	if h.Store == nil || repo == nil || repo.NormalizedFormat() != config.RepositoryFormatCargo {
		return false, nil
	}
	if c.Method() == fiber.MethodPut || c.Method() == fiber.MethodDelete || c.Method() == fiber.MethodPost {
		release := repositorygate.AcquireMutation(repo.Name)
		defer release()
	}
	switch {
	case requestPath == "config.json" && (c.Method() == fiber.MethodGet || c.Method() == fiber.MethodHead):
		return true, h.serveConfig(c, state, repo)
	case requestPath == "api/v1/crates/new" && c.Method() == fiber.MethodPut:
		return true, h.publish(c, state, repo, storagePath)
	}

	parts := strings.Split(strings.Trim(requestPath, "/"), "/")
	if len(parts) >= 3 && parts[0] == "api" && parts[1] == "v1" {
		switch {
		case len(parts) == 3 && parts[2] == "crates" && c.Method() == fiber.MethodGet:
			return true, h.search(c, state, repo)
		case len(parts) == 4 && parts[2] == "me" && parts[3] == "crates" && c.Method() == fiber.MethodGet:
			return true, h.listManagedPackages(c, state, repo)
		case len(parts) == 5 && parts[2] == "invitations" && c.Method() == fiber.MethodPost:
			return true, h.respondInvitation(c, state, repo, parts[3], parts[4])
		case len(parts) >= 4 && parts[2] == "crates":
			return h.handleCrateAPI(c, state, repo, storagePath, parts)
		}
	}
	return false, nil
}

func (h Handler) handleCrateAPI(c fiber.Ctx, state *core.AppState, repo *config.Repository, storagePath string, parts []string) (bool, error) {
	crateName := parts[3]
	deprecationRequest := len(parts) == 5 && parts[4] == "deprecate" && c.Method() == fiber.MethodPut
	if !deprecationRequest && c.Method() != fiber.MethodGet && c.Method() != fiber.MethodHead {
		if err := state.GetDB().EnsurePackageMutable(config.RepositoryFormatCargo, repo.Name,
			normalizeCrateName(crateName)); err != nil {
			return true, cargoError(c, err)
		}
	}
	switch {
	case len(parts) == 4 && c.Method() == fiber.MethodGet:
		return true, h.packageInfo(c, state, repo, storagePath, crateName)
	case len(parts) == 4 && c.Method() == fiber.MethodDelete:
		return true, h.deletePackage(c, state, repo, storagePath, crateName)
	case len(parts) == 5 && parts[4] == "owners" && c.Method() == fiber.MethodGet:
		return true, h.listOwners(c, state, repo, crateName)
	case len(parts) == 5 && parts[4] == "owners" && c.Method() == fiber.MethodPut:
		return true, h.inviteOwners(c, state, repo, crateName)
	case len(parts) == 5 && parts[4] == "owners" && c.Method() == fiber.MethodDelete:
		return true, h.removeOwners(c, state, repo, crateName)
	case len(parts) == 5 && parts[4] == "users" && c.Method() == fiber.MethodGet:
		return true, h.searchUsers(c, state, repo, crateName)
	case len(parts) == 5 && parts[4] == "archive" && c.Method() == fiber.MethodPut:
		return true, h.setPackageArchived(c, state, repo, storagePath, crateName, true)
	case len(parts) == 5 && parts[4] == "archive" && c.Method() == fiber.MethodDelete:
		return true, h.setPackageArchived(c, state, repo, storagePath, crateName, false)
	case deprecationRequest:
		return true, h.deprecatePackage(c, state, repo, crateName)
	case len(parts) == 5 && c.Method() == fiber.MethodDelete:
		return true, h.deleteVersion(c, state, repo, storagePath, crateName, parts[4])
	case len(parts) == 6 && parts[4] == "owners" && c.Method() == fiber.MethodPut:
		return true, h.setOwnerLevel(c, state, repo, crateName, parts[5])
	case len(parts) == 6 && parts[4] == "owners" && c.Method() == fiber.MethodDelete:
		return true, h.removeOwner(c, state, repo, crateName, parts[5])
	case len(parts) == 6 && parts[5] == "yank" && c.Method() == fiber.MethodDelete:
		return true, h.setYanked(c, state, repo, storagePath, crateName, parts[4], true)
	case len(parts) == 6 && parts[5] == "unyank" && c.Method() == fiber.MethodPut:
		return true, h.setYanked(c, state, repo, storagePath, crateName, parts[4], false)
	case len(parts) == 6 && parts[5] == "docs" && c.Method() == fiber.MethodGet:
		return true, h.getDocStatus(c, state, repo, storagePath, crateName, parts[4])
	case len(parts) == 6 && parts[5] == "docs" && (c.Method() == fiber.MethodPut || c.Method() == fiber.MethodPost):
		return true, h.uploadDocs(c, state, repo, storagePath, crateName, parts[4])
	case len(parts) == 6 && parts[5] == "docs" && c.Method() == fiber.MethodDelete:
		return true, h.deleteDocs(c, state, repo, storagePath, crateName, parts[4])
	default:
		return false, nil
	}
}

func cargoIndexPath(storagePath string, repo *config.Repository, crateName string) string {
	return filepath.Join(storagePath, repo.Name, filepath.FromSlash(indexPath(crateName)))
}

func cargoPackageLockPath(storagePath string, repo *config.Repository, crateName string) string {
	return filepath.Join(storagePath, repo.Name, ".renop.tmp.cargo", normalizeCrateName(crateName))
}

func acquireIndexLock(state *core.AppState, lockPath string) (func(bool), error) {
	if state == nil || state.Inner == nil || state.Inner.InFlightDownloads == nil {
		return nil, fiber.ErrServiceUnavailable
	}
	lockKey := filepath.ToSlash(lockPath)
	publication := state.Inner.InFlightDownloads.AcquirePath(lockKey)
	return func(succeeded bool) {
		state.Inner.InFlightDownloads.UnlockPath(lockKey, publication, succeeded)
	}, nil
}

func errorResponse(c fiber.Ctx, statusCode int, detail string) error {
	c.Set(fiber.HeaderContentType, "application/json; charset=utf-8")
	return c.Status(statusCode).JSON(ErrorResponse{Errors: []ErrorDetail{{Detail: detail}}})
}
