/*
 * Copyright (c) 2026 404Setup. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
 */

package auth

import (
	"errors"
	"strings"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"

	"renop/audit"
	"renop/config"
	"renop/core"
	"renop/pb"
	"renop/token"
	"renop/utils"
	"renop/utils/protohttp"
)

const sessionCookieName = "renop_session"

func isSecure(c fiber.Ctx) bool {
	if c.Secure() {
		return true
	}
	if strings.EqualFold(c.Get("X-Forwarded-Proto"), "https") {
		return true
	}
	if strings.Contains(c.Get("CF-Visitor"), `"scheme":"https"`) {
		return true
	}
	return false
}

func setSessionCookie(c fiber.Ctx, value string, maxAge int) {
	secure := isSecure(c)
	if maxAge > 0 {
		cookie := &fiber.Cookie{
			Name:     sessionCookieName,
			Value:    value,
			Path:     "/",
			MaxAge:   maxAge,
			Expires:  time.Now().Add(time.Duration(maxAge) * time.Second),
			HTTPOnly: true,
			SameSite: "Lax",
			Secure:   secure,
		}
		c.Cookie(cookie)
	} else {
		for _, sec := range []bool{true, false} {
			for _, ss := range []string{"Lax", "Strict", "None"} {
				c.Cookie(&fiber.Cookie{
					Name:     sessionCookieName,
					Value:    "",
					Path:     "/",
					MaxAge:   -1,
					Expires:  time.Unix(1, 0),
					HTTPOnly: true,
					SameSite: ss,
					Secure:   sec,
				})
			}
		}
	}
}

func SetupAuthRoutes(app fiber.Router, state *core.AppState, opChan chan<- token.TokenOp) {
	auth := app.Group("/auth")
	auth.Post("/login", func(c fiber.Ctx) error { return PostAuthLogin(c, state, opChan) })
	auth.Post("/logout", func(c fiber.Ctx) error { return PostAuthLogout(c, state) })
	auth.Get("/me", func(c fiber.Ctx) error { return GetAuthMe(c) })
	auth.Put("/profile/password", func(c fiber.Ctx) error { return UpdatePassword(c, state, opChan) })
	auth.Post("/profile/token", func(c fiber.Ctx) error { return GenerateUploadToken(c, state, opChan) })
	auth.Get("/profile/sessions", func(c fiber.Ctx) error { return ListSessions(c, state) })
	auth.Post("/profile/sessions/revoke-others", func(c fiber.Ctx) error { return RevokeOtherSessions(c, state) })
	auth.Delete("/profile/sessions/:session_id", func(c fiber.Ctx) error { return DeleteSession(c, state) })
	SetupFidoRoutes(auth, state)
}

func CreateSessionDetails(user *config.User, sessionToken string) core.SessionDetails {
	permissions := make([]core.AccessTokenPermission, 0, len(user.Roles)+1)
	routes := make([]core.Route, 0, len(user.ReadPermissions)+len(user.WritePermissions)+2)

	if user.IsManager() {
		permissions = append(permissions, core.AccessTokenPermission{
			Identifier: "access-token:manager",
			Shortcut:   "m",
		})
	}

	for _, role := range user.Roles {
		shortcut := " "
		if len(role) > 0 {
			shortcut = string(role[0])
		}
		permissions = append(permissions, core.AccessTokenPermission{
			Identifier: role,
			Shortcut:   shortcut,
		})
	}

	for _, perm := range user.ReadPermissions {
		routes = append(routes, core.Route{
			Path: perm,
			Permission: core.RoutePermission{
				Identifier: "route:read",
				Shortcut:   "r",
			},
		})
	}

	for _, perm := range user.WritePermissions {
		routes = append(routes, core.Route{
			Path: perm,
			Permission: core.RoutePermission{
				Identifier: "route:write",
				Shortcut:   "w",
			},
		})
	}

	if user.IsManager() {
		hasFullWrite := false
		for _, r := range routes {
			if r.Permission.Identifier == "route:write" && r.Path == "*" {
				hasFullWrite = true
				break
			}
		}
		if !hasFullWrite {
			routes = append(routes, core.Route{
				Path: "*",
				Permission: core.RoutePermission{
					Identifier: "route:write",
					Shortcut:   "w",
				},
			})
		}
	}

	accessToken := core.AccessTokenDto{
		Identifier: core.AccessTokenIdentifier{
			Type:  core.Persistent,
			Value: 0,
		},
		Name:        user.Username,
		CreatedAt:   time.Now().UTC().Format(time.RFC3339),
		Description: "Autogenerated session token",
		ExpiresAt:   nil,
		Tokens:      []string{},
	}

	return core.SessionDetails{
		AccessToken:  accessToken,
		Permissions:  permissions,
		Routes:       routes,
		SessionToken: sessionToken,
	}
}

func AuthenticateUser(state *core.AppState, body *core.LoginRequest, opChan chan<- token.TokenOp) (*config.User, error) {
	if len(body.Name) == 0 || len(body.Name) > 128 || len(body.Secret) == 0 || len(body.Secret) > 72 {
		return nil, nil
	}
	isEmpty := state.Inner.TokensCount.Load() == 0

	if isEmpty {
		token.AutoRegisterAdmin(state, opChan)
	}

	accessToken := state.GetTokenByName(strings.ToLower(body.Name))
	if accessToken != nil {
		if accessToken.ExpiresAt != nil {
			if time.Now().UnixMilli() > *accessToken.ExpiresAt {
				return nil, fiber.ErrForbidden
			}
		}

		err := bcrypt.CompareHashAndPassword([]byte(accessToken.EncryptedSecret), []byte(body.Secret))
		if err == nil {
			synthUser := buildSynthUser(accessToken)
			synthUser.Tokens = []string{"Bearer " + body.Name + ":" + body.Secret}
			return synthUser, nil
		}
	}

	return nil, nil
}

func PostAuthLogin(c fiber.Ctx, state *core.AppState, opChan chan<- token.TokenOp) error {
	cfgVal := state.Inner.Config.Load()
	cfg := cfgVal.(*config.Config)
	ip := utils.ExtractIP(c, &cfg.Server)
	userAgent := c.Get(fiber.HeaderUserAgent, "Unknown")

	var req pb.LoginRequest
	if err := protohttp.Read(c, &req); err != nil {
		return c.Status(fiber.StatusBadRequest).SendString("Bad Request")
	}
	body := core.LoginRequest{
		Name:   req.GetName(),
		Secret: req.GetSecret(),
	}

	user, err := AuthenticateUser(state, &body, opChan)
	if errors.Is(err, fiber.ErrForbidden) {
		return c.Status(fiber.StatusForbidden).SendString("Forbidden")
	}

	if user != nil {
		sessionToken := uuid.NewString()
		publicId := uuid.NewString()
		now := time.Now().UnixMilli()

		session := &core.Session{
			PublicId:    publicId,
			Username:    user.Username,
			Ip:          utils.Intern(ip),
			UserAgent:   utils.Intern(userAgent),
			CreatedAt:   now,
			LoginMethod: "password",
		}
		session.LastActive.Store(now)

		state.SaveSession(session, sessionToken)

		audit.Log(state, &core.AuditLogEntry{
			Username:   user.Username,
			Operator:   user.Username,
			Action:     "LOGIN",
			Details:    "User logged in successfully",
			AuthMethod: "Password",
			SessionID:  publicId,
			IP:         ip,
		})

		setSessionCookie(c, sessionToken, int(core.SessionIdleTimeoutMillis/1000))
		details := CreateSessionDetails(user, "")
		return protohttp.Write(c, pb.FromSessionDetails(details))
	}

	return c.Status(fiber.StatusUnauthorized).SendString("Unauthorized")
}

func GetAuthMe(c fiber.Ctx) error {
	userInt := c.Locals("user")
	var user *config.User
	if userInt != nil {
		user = userInt.(*config.User)
	} else {
		user = GuestUser
	}

	if user.Username == "guest" {
		return c.Status(fiber.StatusUnauthorized).SendString("Unauthorized")
	}

	authHeader := c.Get(fiber.HeaderAuthorization, "")
	sessionToken := strings.TrimPrefix(authHeader, "Session ")
	if sessionToken == authHeader {
		sessionToken = ""
	}

	details := CreateSessionDetails(user, sessionToken)
	if currentSession, ok := c.Locals("current_session_id").(string); ok && currentSession != "" {
		if c.Cookies(sessionCookieName) != currentSession {
			setSessionCookie(c, currentSession, int(core.SessionIdleTimeoutMillis/1000))
		}
	}
	return protohttp.Write(c, pb.FromSessionDetails(details))
}

func resolveLogoutSessionToken(c fiber.Ctx) string {
	if id, ok := c.Locals("current_session_id").(string); ok {
		if id = strings.TrimSpace(id); id != "" {
			return id
		}
	}
	if cookie := strings.TrimSpace(c.Cookies(sessionCookieName)); cookie != "" {
		return cookie
	}
	authHeader := c.Get(fiber.HeaderAuthorization, "")
	if after, ok := strings.CutPrefix(authHeader, "Session "); ok {
		if id := strings.TrimSpace(after); id != "" {
			return id
		}
	}
	return ""
}

func PostAuthLogout(c fiber.Ctx, state *core.AppState) error {
	user := GetUser(c)
	if sessionID := resolveLogoutSessionToken(c); sessionID != "" {
		state.RevokeSession(sessionID)
	}
	if user != nil && user.Username != "" && user.Username != "guest" {
		_, op, authMethod, sessionID, ip := audit.ExtractAuthDetails(c)
		audit.Log(state, &core.AuditLogEntry{
			Username:   user.Username,
			Operator:   op,
			Action:     "LOGOUT",
			Details:    "User logged out",
			AuthMethod: authMethod,
			SessionID:  sessionID,
			IP:         ip,
		})
	}
	setSessionCookie(c, "", -1)
	return c.SendStatus(fiber.StatusNoContent)
}
