// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0--rc3
// source: storage/v1/session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoredSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActive    int64                  `protobuf:"varint,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredSession) Reset() {
	*x = StoredSession{}
	mi := &file_storage_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredSession) ProtoMessage() {}

func (x *StoredSession) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredSession.ProtoReflect.Descriptor instead.
func (*StoredSession) Descriptor() ([]byte, []int) {
	return file_storage_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *StoredSession) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *StoredSession) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StoredSession) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StoredSession) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StoredSession) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *StoredSession) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StoredSession) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

type SessionStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Sessions      []*StoredSession       `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStore) Reset() {
	*x = SessionStore{}
	mi := &file_storage_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStore) ProtoMessage() {}

func (x *SessionStore) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStore.ProtoReflect.Descriptor instead.
func (*SessionStore) Descriptor() ([]byte, []int) {
	return file_storage_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStore) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SessionStore) GetSessions() []*StoredSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_storage_v1_session_proto protoreflect.FileDescriptor

const file_storage_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/session.proto\x12\x10renop.storage.v1\"\xdc\x01\n" +
	"\rStoredSession\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vlast_active\x18\a \x01(\x03R\n" +
	"lastActive\"r\n" +
	"\fSessionStore\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12;\n" +
	"\bsessions\x18\x02 \x03(\v2\x1f.renop.storage.v1.StoredSessionR\bsessionsB\n" +
	"Z\brenop/pbb\x06proto3"

var (
	file_storage_v1_session_proto_rawDescOnce sync.Once
	file_storage_v1_session_proto_rawDescData []byte
)

func file_storage_v1_session_proto_rawDescGZIP() []byte {
	file_storage_v1_session_proto_rawDescOnce.Do(func() {
		file_storage_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_session_proto_rawDesc), len(file_storage_v1_session_proto_rawDesc)))
	})
	return file_storage_v1_session_proto_rawDescData
}

var file_storage_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storage_v1_session_proto_goTypes = []any{
	(*StoredSession)(nil), // 0: renop.storage.v1.StoredSession
	(*SessionStore)(nil),  // 1: renop.storage.v1.SessionStore
}
var file_storage_v1_session_proto_depIdxs = []int32{
	0, // 0: renop.storage.v1.SessionStore.sessions:type_name -> renop.storage.v1.StoredSession
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storage_v1_session_proto_init() }
func file_storage_v1_session_proto_init() {
	if File_storage_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_session_proto_rawDesc), len(file_storage_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_v1_session_proto_goTypes,
		DependencyIndexes: file_storage_v1_session_proto_depIdxs,
		MessageInfos:      file_storage_v1_session_proto_msgTypes,
	}.Build()
	File_storage_v1_session_proto = out.File
	file_storage_v1_session_proto_goTypes = nil
	file_storage_v1_session_proto_depIdxs = nil
}
